import { validateProject, STYLE_KEYS, EFFECTS } from '../config/validation.js';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sections={overview:'Overview',ui:'Interface',animations:'Animations',features:'Feature map',entities:'Entities',cards:'Cards & decks',assets:'Assets',debug:'Debug sandbox'};
let base=await(await fetch('/app/config/project.json')).text(), config=JSON.parse(base);
const defaults=await(await fetch('/app/config/defaults.json')).json();
let assets=await(await fetch('/__editor/assets')).json(),section='overview',selected=null,group='cards',dirty=false,inspect=false,ready=false,pending=new Map(),sequence=0,history=[],latestState=null;
const frame=$('gameFrame');
function status(message,error=false){$('status').textContent=message;$('status').style.background=error?'#ffe1ce':'#e5eddf';}
function rpc(type,payload){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Preview did not respond. Reload the preview.'));},15000);pending.set(id,{resolve,reject,timer});frame.contentWindow.postMessage({editor:true,id,type,payload},location.origin);});}
function preview(){if(ready)void rpc('config',config).catch(e=>status(e.message,true));}
function change(mutator){const previous=structuredClone(config);try{mutator();validateProject(config);history.push(previous);history=history.slice(-40);dirty=true;localStorage.setItem('ek-editor-draft-v1',JSON.stringify(config));preview();status('Unsaved draft · preview updated. Save project to write configuration.');}catch(error){config=previous;status(error.message,true);return false;}return true;}
window.addEventListener('message',event=>{
  if(event.origin!==location.origin||event.source!==frame.contentWindow||!event.data?.editor)return;
  const m=event.data;
  if(m.type==='ready'){ready=true;preview();if(inspect)void rpc('inspect',true);}
  if(m.type==='reply'){const p=pending.get(m.id);if(!p)return;clearTimeout(p.timer);pending.delete(m.id);if(m.error)p.reject(new Error(m.error));else{latestState=m.result.state;p.resolve(m.result);}}
  if(m.type==='inspection'){inspect=false;$('inspect').textContent='Inspect element';document.querySelector('.preview').classList.remove('inspecting');void rpc('inspect',false);$('inspection').hidden=false;$('inspection').textContent=JSON.stringify(m.detail,null,2);if(m.item){section='ui';selected=m.item;render();}}
});
const field=(key,label,value,kind='text',options=[],help='')=>`<label class="field">${esc(label)}${kind==='select'?`<select data-field="${key}">${options.map(v=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(v)}</option>`).join('')}</select>`:kind==='json'?`<textarea data-field="${key}" data-kind="json">${esc(JSON.stringify(value===undefined?{}:value,null,2))}</textarea>`:kind==='textarea'?`<textarea data-field="${key}">${esc(value)}</textarea>`:`<input data-field="${key}" type="${kind}" ${kind==='checkbox'?(value?'checked':''):`value="${esc(value)}"`} ${kind==='number'?'step="any"':''}>`}${help?`<span class="help">${esc(help)}</span>`:''}</label>`;
function sourceLinks(item){return `<h3>Trace to implementation</h3>${[item.source,...(item.references||[]),{file:'app/config/project.json',symbol:`"id": "${item.id}"`}].filter(Boolean).map(ref=>`<button class="ref" data-source="${esc(ref.file)}" data-symbol="${esc(ref.symbol)}">${esc(ref.file)} → ${esc(ref.symbol)} ↗</button>`).join('')}`;}
function link(id){const category=Object.keys(config).find(k=>Array.isArray(config[k])&&config[k].some(x=>x.id===id));return category?`<button data-related="${esc(id)}" data-category="${category}">${esc(config[category].find(x=>x.id===id).name)}</button>`:`<span class="badge">${esc(id)}</span>`;}
function relations(item){const values=[...(item.entities||[]),...(item.animations||[]),...(item.sounds||[]),...(item.components||[]),...(item.dependencies||[]),item.animation,item.sound,item.feature,item.component].filter(Boolean);const incoming=[];for(const [g,list]of Object.entries(config))if(Array.isArray(list))for(const x of list)if(x.id!==item.id&&JSON.stringify(x).includes(`"${item.id}"`))incoming.push(x.id);return `<h3>Relationships</h3><div class="relations">${link(item.id)} → ${[...new Set(values)].map(link).join(' → ')||'<span class="muted">See source reference</span>'}</div><h3>Used by</h3><div class="relations">${[...new Set(incoming)].map(link).join('')||'<span class="muted">No configured references</span>'}</div>`;}
function navigation(){ $('nav').innerHTML='<small>INSPECT / CREATE / TEST</small>'+Object.entries(sections).map(([id,name])=>`<button data-section="${id}" class="${section===id?'selected':''}">${name}</button>`).join('');$('nav').querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;selected=null;$('search').value='';render();}); }
function collection(){if(section==='cards')return config[group];if(section==='assets')return assets;if(section==='entities')return [...config.entities,...config.sounds];return config[section]||[];}
function render(){navigation();$('title').textContent=sections[section];$('sectionActions').innerHTML='';$('list').innerHTML='';$('detail').innerHTML='';
  if(section==='overview')return overview();if(section==='debug')return debug();
  const query=$('search').value.trim().toLowerCase();let items;
  if(query){items=[...Object.entries(config).flatMap(([category,list])=>Array.isArray(list)?list.map(x=>({...x,_category:category})):[]),...assets.map(x=>({...x,_category:'assets'}))].filter(x=>JSON.stringify(x).toLowerCase().includes(query));$('title').textContent=`Search · ${query}`;}
  else items=collection().map(x=>({...x,_category:section==='cards'?group:section==='entities'?(config.sounds.includes(x)?'sounds':'entities'):section}));
  if(section==='cards'&&!query)$('sectionActions').innerHTML=`<button id="cardsTab">Cards</button> <button id="decksTab">Decks</button> <button id="add">+ Create ${group==='cards'?'card':'deck'}</button>`;
  else if(['ui','entities','animations'].includes(section)&&!query)$('sectionActions').innerHTML='<button id="add">+ Add entity</button>';
  else if(section==='assets')$('sectionActions').innerHTML='<button id="upload">+ Upload asset</button>';
  if(!items.some(i=>i.id===selected))selected=items[0]?.id;
  $('list').innerHTML=items.map(i=>`<button class="item ${selected===i.id?'selected':''}" data-item="${esc(i.id)}" data-category="${i._category}">${i.art?`<img src="${esc(i.art)}" alt="">`:''}${esc(i.name)}<small>${esc(i._category)} · ${esc(i.id)}</small></button>`).join('')||'<div class="empty">No matches.</div>';
  $('list').querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=b.dataset.item;renderDetail(b.dataset.category,b.dataset.item);$('list').querySelectorAll('.item').forEach(x=>x.classList.toggle('selected',x===b));});
  const item=items.find(i=>i.id===selected);if(item)renderDetail(item._category,item.id);
  $('cardsTab')?.addEventListener('click',()=>{group='cards';selected=null;render();});$('decksTab')?.addEventListener('click',()=>{group='decks';selected=null;render();});
  $('add')?.addEventListener('click',()=>addItem(section==='cards'?group:section));$('upload')?.addEventListener('click',()=>$('assetUpload').click());
}
function renderDetail(category,id){const item=(category==='assets'?assets:config[category]).find(i=>i.id===id);if(!item)return;selected=id;
  let body=`<h2>${esc(item.name)}</h2>`;
  if(category==='features'){body+=`<span class="badge">${esc(item.status)}</span><p>${esc(item.description)}</p>${relations(item)}${sourceLinks(item)}`;}
  else if(category==='assets'){body+=assetDetail(item);}
  else {
    body+=`<div class="row"><button id="duplicate">Duplicate</button><button id="delete">Delete</button></div>`;
    if(category==='cards')body+=`<img class="card-preview" src="${esc(item.art)}" alt="${esc(item.name)}">`;
    body+=field('name','Name',item.name)+field('id','ID',item.id)+field('enabled','Enabled',item.enabled,'checkbox');
    if(category==='cards')body+=field('art','Artwork path',item.art)+field('icon','Icon path',item.icon)+field('description','Description',item.description,'textarea')+field('rule','Rules / detail text',item.rule,'textarea')+field('color','Color',item.color,'color')+field('count','Default quantity',item.count,'number',[],'Deck quantities below control new games.')+field('effect','Effect / family',item.effect,'select',EFFECTS)+field('animation','Animation',item.animation,'select',['',...config.animations.map(a=>a.id)])+field('sound','Sound',item.sound,'select',['',...config.sounds.map(a=>a.id)])+field('uiBehavior','Card UI behavior',item.uiBehavior,'select',['card-face','icon','text'])+`<p class="muted">Play condition: ${esc(item.playCondition)} · Target: ${esc(item.targetRequirement)} · UI: ${esc(item.uiBehavior)}. Conditions follow the supported engine effect.</p><h3>Deck membership / quantity</h3>${config.decks.map(d=>`<label class="field">${esc(d.name)}<input type="number" min="0" max="200" value="${d.cards[id]||0}" data-membership="${d.id}"></label>`).join('')}`;
    if(category==='decks')body+=field('description','Description',item.description)+field('cards','Card IDs → quantities',item.cards,'json',[],'Zero removes a card from this deck. Enabled decks require enough cards for 2–5 players.')+`<button id="useDeck">New sandbox with this deck</button>`;
    if(category==='ui')body+=field('selector','CSS selector',item.selector)+field('text','Text override',item.text)+field('asset','Image asset override',item.asset)+`<label class="field">Add style property<select id="styleProperty">${STYLE_KEYS.map(k=>`<option>${k}</option>`).join('')}</select><input id="styleValue" placeholder="Value, e.g. 24px"><button id="addStyle">Set style</button></label>`+['styles','hover','active','disabled','mobile','tablet','desktop'].map(key=>field(key,key==='styles'?'Base CSS styles':`${key} styles`,item[key],'json')).join('');
    if(category==='animations')body+=`<p>${esc(item.description)}</p><p class="muted">Trigger: ${esc(item.trigger)} · Component: ${esc(item.component)} · Sound: ${esc(item.sound||'none')}</p><div class="row">${['play','replay','pause','slow','resume','reset'].map(a=>`<button data-animation="${a}">${a==='slow'?'Slow motion':a[0].toUpperCase()+a.slice(1)}</button>`).join('')}</div><button id="resetAnimation">Restore default properties</button>`+['duration','delay','speed','distance','scale','rotation','opacity','intensity'].map(key=>field(key,`${key}${['duration','delay'].includes(key)?' (ms)':''}`,item[key],'number')).join('')+field('easing','Easing',item.easing)+field(item.cssFrames?'cssFrames':'keyframes',item.cssFrames?'CSS keyframes':'Keyframes override (null uses measured game path)',item.cssFrames||item.keyframes,'json',[],'Flights keep DOM-measured source/destination paths unless overridden. CSS effects use their actual keyframe definitions.');
    if(category==='sounds')body+=field('frequency','Synth frequency (Hz)',item.frequency,'number')+field('volume','Volume (0–0.2)',item.volume,'number')+field('asset','Audio path (blank uses synth)',item.asset)+`<button id="playSound">Play sound</button>`;
    if(category==='entities')body+=field('kind','Entity kind',item.kind,'select',['player','bot','notification','effect','game-object','font','music'])+field('asset','Asset path',item.asset)+field('properties','CSS properties',item.properties,'json')+field('behavior','Behavior configuration',item.behavior,'json',[],'Bots: difficulty = inherit / casual / clever. Font: name becomes its CSS family. Music: volume = 0–0.2; follows game sound setting. Player: default setup name. Other entities: static presentation objects.');
    body+=relations(item)+sourceLinks(item);
  }
  $('detail').innerHTML=body;
  $('detail').querySelectorAll('[data-field]').forEach(input=>input.onchange=()=>{
    const key=input.dataset.field;let value;
    try{value=input.dataset.kind==='json'?JSON.parse(input.value):input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;}catch(e){status(`Invalid JSON in ${key}.`,true);return;}
    const oldId=item.id;
    if(change(()=>{const current=config[category].find(x=>x.id===oldId);current[key]=value;if(key==='effect'){current.family=value;current.playCondition=['defuse','exploding-kitten'].includes(value)?'danger':value==='nope'?'reaction':'turn';current.targetRequirement=value==='favor'?'other-player':value==='attack-2x'?'clockwise':'none';}if(key==='id')renameRefs(oldId,value,category);if(key==='count'&&category==='cards')for(const d of config.decks)if(d.cards[oldId]!==undefined)d.cards[oldId]=value;})){selected=key==='id'?value:oldId;if(['id','effect','enabled'].includes(key))render();}
  });
  $('detail').querySelectorAll('[data-field]').forEach(input=>{if(input.dataset.field!=='id')input.oninput=input.onchange;});
  $('detail').querySelectorAll('[data-membership]').forEach(input=>input.onchange=()=>change(()=>{config.decks.find(d=>d.id===input.dataset.membership).cards[id]=Number(input.value);}));
  $('detail').querySelectorAll('[data-membership]').forEach(input=>input.oninput=input.onchange);
  $('addStyle')?.addEventListener('click',()=>{if(change(()=>{config.ui.find(u=>u.id===id).styles[$('styleProperty').value]=$('styleValue').value;}))renderDetail(category,id);});
  $('duplicate')?.addEventListener('click',()=>duplicate(category,id));$('delete')?.addEventListener('click',()=>deleteItem(category,id));
  $('useDeck')?.addEventListener('click',()=>runDebug({action:'new',bots:3,deck:id}));
  $('detail').querySelectorAll('[data-animation]').forEach(b=>b.onclick=()=>rpc('animation',{action:b.dataset.animation,id}).catch(e=>status(e.message,true)));
  $('resetAnimation')?.addEventListener('click',()=>{const original=defaults.animations.find(a=>a.id===id);if(original&&change(()=>Object.assign(config.animations.find(a=>a.id===id),structuredClone(original))))renderDetail(category,id);});
  $('playSound')?.addEventListener('click',()=>playSound(item));
  wireReferences();
}
function renameRefs(oldId,newId,category){
  if(category==='cards')for(const d of config.decks)if(Object.hasOwn(d.cards,oldId)){d.cards[newId]=d.cards[oldId];delete d.cards[oldId];}
  const keys=category==='animations'?['animation','animations']:category==='sounds'?['sound','sounds']:category==='features'?['feature','dependencies']:['entities','components','component'];
  for(const collection of ['ui','entities','features','cards','animations'])for(const item of config[collection])for(const key of keys){if(item[key]===oldId)item[key]=newId;else if(Array.isArray(item[key]))item[key]=item[key].map(x=>x===oldId?newId:x);}
}
function unique(category,prefix){let id=prefix,n=2;while(config[category].some(x=>x.id===id))id=`${prefix}-${n++}`;return id;}
function duplicate(category,id){const item=config[category].find(x=>x.id===id);if(category==='cards'&&['defuse','nope','exploding-kitten'].includes(item.effect)){status('Duplicate an ordinary action or cat card; rescue, Nope and Kitten identities are fixed by the engine.',true);return;}const copy=structuredClone(item);copy.id=unique(category,`${id}-copy`);copy.name+=' copy';if(change(()=>config[category].push(copy))){selected=copy.id;render();}}
function deleteItem(category,id){if(change(()=>{config[category]=config[category].filter(x=>x.id!==id);if(category==='cards')for(const d of config.decks)delete d.cards[id];if(category==='sounds')for(const c of config.cards)if(c.sound===id)c.sound='';if(category==='animations')for(const c of config.cards)if(c.animation===id)c.animation='';})){selected=null;render();}}
function addItem(category){if(category==='cards'){const copy=structuredClone(config.cards.find(c=>c.effect==='skip'));copy.id=unique(category,'new-card');copy.name='New Skip variant';copy.count=0;copy.source={file:'app/engine.js',symbol:'resolve'};if(change(()=>config.cards.push(copy))){selected=copy.id;render();}return;}if(category==='decks'){duplicate(category,config.decks[0].id);return;}if(category==='ui'){const item={...structuredClone(config.ui[0]),id:unique(category,'new-ui'),name:'New UI component',selector:'.configured-entity',styles:{},source:{file:'app/config/runtime.js',symbol:'applyPresentation'}};if(change(()=>config.ui.push(item))){selected=item.id;render();}return;}if(category==='animations'){duplicate(category,config.animations[0].id);return;}const item={id:unique('entities','new-object'),name:'New game object',kind:'game-object',enabled:true,asset:'',properties:{position:'absolute',left:'20px',top:'200px',padding:'12px',background:'#fff8e9','z-index':'3'},behavior:{},source:{file:'app/config/runtime.js',symbol:'applyPresentation'}};if(change(()=>config.entities.push(item))){selected=item.id;render();}}
function assetDetail(item){const uses=[];for(const [category,list]of Object.entries(config))if(Array.isArray(list))for(const entity of list)if(JSON.stringify(entity).includes(item.path))uses.push({category,entity});return `${item.kind==='image'?`<img class="asset-preview" src="${esc(item.path)}" alt="${esc(item.name)}">`:item.kind==='audio'?`<audio controls src="${esc(item.path)}"></audio>`:`<p>Font asset</p>`}<p class="muted">${esc(item.path)}</p><h3>Usage / reference chain</h3>${uses.map(({category,entity})=>`<p>${esc(item.name)} → ${link(entity.id)} → ${entity.animation?link(entity.animation):'<span class="badge">'+esc(category)+'</span>'}</p>`).join('')||'<p class="muted">Available library asset; no active configuration reference.</p>'}<label class="field">Replacement asset path<input id="replacement" list="assetPaths" value="${esc(item.path)}"><datalist id="assetPaths">${assets.map(a=>`<option value="${esc(a.path)}">`).join('')}</datalist></label><button id="replaceAsset">Replace all references</button><p class="muted">Original downloaded files remain intact. References change in the project configuration.</p><button class="ref" data-source="app/config/runtime.js" data-symbol="applyPresentation">app/config/runtime.js → applyPresentation ↗</button>`;}
function wireReferences(){document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>showSource(b.dataset.source,b.dataset.symbol));document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>{const c=b.dataset.category;section=['cards','decks'].includes(c)?'cards':c==='sounds'?'entities':c;group=c==='decks'?'decks':'cards';selected=b.dataset.related;$('search').value='';render();});$('replaceAsset')?.addEventListener('click',()=>{const previous=selected,next=$('replacement').value;if(change(()=>{const substitute=v=>typeof v==='string'?v.split(previous).join(next):Array.isArray(v)?v.map(substitute):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,substitute(x)])):v;config=substitute(config);})){renderDetail('assets',previous);}});}
async function showSource(file,symbol){try{const response=await fetch(`/__editor/source?file=${encodeURIComponent(file)}`),data=await response.json();if(!response.ok)throw new Error(data.error);$('sourceTitle').textContent=`${file} → ${symbol}`;$('sourceText').innerHTML=data.text.split('\n').map((line,i)=>`<span class="${line.includes(symbol)?'highlight':''}">${String(i+1).padStart(4)}  ${esc(line)}</span>`).join('\n');$('sourceDialog').showModal();$('sourceText').querySelector('.highlight')?.scrollIntoView({block:'center'});}catch(e){status(e.message,true);}}
function overview(){ $('list').innerHTML='';$('detail').innerHTML=`<div class="overview"><span class="badge">LOCAL PROJECT · ORIGINAL EDITION</span><h2 style="font-size:30px;margin-top:15px">One place to shape the table.</h2><p>Inspect the running interface, tune real animation settings, create cards and decks, trace features to their source, and rehearse game situations in a separate sandbox.</p><div class="stats">${[['Cards',config.cards.length],['Decks',config.decks.length],['Animations',config.animations.length],['Features',config.features.length],['UI components',config.ui.length],['Assets',assets.length]].map(([name,count])=>`<div class="stat"><strong>${count}</strong>${name}</div>`).join('')}</div><div class="panel"><h3 style="margin-top:0">Theme tokens</h3>${field('theme','CSS variables / typography',config.theme,'json',[],'Examples: --ink, --cream, --yellow, --card-w, --card-h. Use Interface for fonts and backgrounds.')}</div><div class="row"><button id="undo">Undo last edit</button><button id="discard">Discard draft</button><button id="recover">Recover browser draft</button><button id="factory">Load default configuration</button></div><div class="panel"><strong>Architecture</strong><p>Configuration → catalog / UI / motion / audio → game engine and rendering. The editor consumes these same systems. Core mechanics remain in app/engine.js, and the editor bridge loads only in this sandbox.</p><button class="ref" data-source="app/engine.js" data-symbol="transition">app/engine.js → transition ↗</button><button class="ref" data-source="app/config/runtime.js" data-symbol="applyPresentation">app/config/runtime.js → applyPresentation ↗</button></div><p class="muted">Save writes app/config/project.json with a backup and detects concurrent changes. New games use new deck inventories; existing saves retain their snapshot. Uploaded files are stored separately from the original Assets library.</p></div>`;
  $('detail').querySelector('[data-field]').onchange=e=>{try{const next=JSON.parse(e.target.value);change(()=>config.theme=next);}catch{status('Invalid theme JSON.',true);}};
  $('undo').onclick=()=>{if(history.length){config=history.pop();dirty=true;preview();render();status('Undo applied · unsaved draft.');}};
  $('discard').onclick=()=>{config=JSON.parse(base);dirty=false;preview();render();status('Draft discarded; loaded saved project.');};
  $('recover').onclick=()=>{try{const recovered=JSON.parse(localStorage.getItem('ek-editor-draft-v1'));if(change(()=>config=recovered))render();}catch{status('No valid browser draft found.',true);}};
  $('factory').onclick=()=>{if(change(()=>config=structuredClone(defaults)))render();};wireReferences();}
async function runDebug(payload){try{status('Running sandbox control…');const result=await rpc('debug',payload);latestState=result.state;status('Sandbox updated · normal game save is unchanged.');if(section==='debug')renderDebugState();}catch(e){status(e.message,true);}}
function debug(){ $('detail').innerHTML=`<div class="overview"><div class="danger-note">Developer sandbox. Card moves conserve the inventory. Controls use the real engine; new table / spawn resets this sandbox.</div><div class="row">${field('bots','Bots',3,'select',['1','2','3','4'])}${field('deck','Deck',config.decks.find(d=>d.enabled).id,'select',config.decks.filter(d=>d.enabled).map(d=>d.id))}</div><button data-debug="new">New sandbox table</button> <button data-debug="spawn">Spawn bots / reset table</button><div class="row">${field('player','Seat ID',0,'number')}${field('card','Card',config.cards[0].id,'select',config.cards.map(c=>c.id))}</div><div class="row">${[['give','Give card'],['remove','Remove card'],['current','Set current seat'],['kitten','Force Kitten draw'],['defuse','Force Defuse'],['attack','Trigger Attack'],['nope','Trigger Nope'],['future','See the Future'],['eliminate','Eliminate seat'],['bot','Force bot action'],['gameover','Make seat winner']].map(([id,name])=>`<button data-debug="${id}">${name}</button>`).join('')}</div><h3>Engine command</h3><p class="muted">Finish responses with PASS, close peeks with CLOSE_FUTURE, reinsert with INSERT. Reaction timing in normal play remains three seconds.</p><textarea id="command" class="debug-state" style="width:100%;height:80px">{"type":"DRAW","player":0}</textarea><button id="dispatch">Dispatch engine command</button><h3>Deck order (UIDs)</h3><textarea id="deckOrder" class="debug-state" style="width:100%;height:100px"></textarea><button data-debug="order">Apply deck order</button><h3>Live sandbox state</h3><button id="refreshState">Refresh state</button><pre id="debugState" class="debug-state">Create a sandbox table to begin.</pre><button class="ref" data-source="app/editor/bridge.js" data-symbol="debug">app/editor/bridge.js → debug ↗</button><button class="ref" data-source="app/engine.js" data-symbol="transition">app/engine.js → transition ↗</button></div>`;
  document.querySelectorAll('[data-debug]').forEach(b=>b.onclick=()=>runDebug({action:b.dataset.debug,bots:$('detail').querySelector('[data-field=bots]').value,deck:$('detail').querySelector('[data-field=deck]').value,player:$('detail').querySelector('[data-field=player]').value,card:$('detail').querySelector('[data-field=card]').value,order:$('deckOrder').value}));
  $('dispatch').onclick=()=>{try{runDebug({action:'command',command:JSON.parse($('command').value)});}catch{status('Invalid command JSON.',true);}};
  $('refreshState').onclick=()=>rpc('state',null).then(r=>{latestState=r.state;renderDebugState();}).catch(e=>status(e.message,true));renderDebugState();wireReferences();}
function renderDebugState(){if(!latestState||!$('debugState'))return;$('debugState').textContent=JSON.stringify({phase:latestState.phase,current:latestState.current,turnsRemaining:latestState.turnsRemaining,winner:latestState.winner,pending:latestState.pending,players:latestState.players.map(p=>({id:p.id,name:p.name,alive:p.alive,hand:p.hand})),deck:latestState.deck},null,2);$('deckOrder').value=latestState.deck.map(c=>c.uid).join('\n');}
function playSound(item){if(!item.enabled)return;if(item.asset){const a=new Audio(item.asset);a.volume=item.volume;void a.play().catch(e=>status(e.message,true));return;}const audio=new AudioContext(),osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(item.frequency,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(item.frequency*(item.id==='danger'?.45:1.3),audio.currentTime+.13);gain.gain.setValueAtTime(Math.max(.001,item.volume),audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.19);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+.2);osc.onended=()=>audio.close();}
$('search').oninput=()=>{if($('search').value&&['overview','debug'].includes(section))section='features';render();};
$('save').onclick=async()=>{try{validateProject(config);const response=await fetch('/__editor/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:config,base})}),result=await response.json();if(!response.ok)throw new Error(result.error);base=result.text;dirty=false;status(`Saved project · backup: ${result.backup}. Reload the normal game to use it.`);}catch(e){status(e.message,true);}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='kitten-studio-project.json';a.click();URL.revokeObjectURL(url);};
$('import').onchange=async event=>{try{const imported=JSON.parse(await event.target.files[0].text());if(change(()=>config=imported)){selected=null;render();}}catch(e){status(e.message,true);}event.target.value='';};
$('assetUpload').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>8000000)throw new Error('Asset maximum is 8 MB.');const reader=new FileReader();const data=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const response=await fetch('/__editor/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,data})}),result=await response.json();if(!response.ok)throw new Error(result.error);assets=await(await fetch('/__editor/assets')).json();section='assets';selected=result.path;render();status(`Uploaded ${file.name} → ${result.path}. Assign it to a card, UI or sound.`);}catch(e){status(e.message,true);}event.target.value='';};
$('inspect').onclick=()=>{inspect=!inspect;$('inspect').textContent=inspect?'Click game element…':'Inspect element';document.querySelector('.preview').classList.toggle('inspecting',inspect);void rpc('inspect',inspect).catch(e=>status(e.message,true));};
function sizeFrame(){const wrap=document.querySelector('.frame-wrap'),mode=$('viewport').value,width=mode==='mobile'?390:mode==='tablet'?900:1366,height=mode==='mobile'?844:768,scale=Math.min(1,(wrap.clientWidth-24)/width);frame.style.width=width+'px';frame.style.height=height+'px';frame.style.transform=`scale(${scale})`;frame.style.marginRight=`${-width*(1-scale)}px`;frame.style.marginBottom=`${-height*(1-scale)}px`;}
$('viewport').onchange=sizeFrame;new ResizeObserver(sizeFrame).observe(document.querySelector('.frame-wrap'));$('reload').onclick=()=>{ready=false;frame.src='/?editor=1&refresh='+Date.now();};$('closeSource').onclick=()=>$('sourceDialog').close();window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
validateProject(config);render();status('Project loaded · edits preview live; Save project writes to disk.');
